version: "3.7"
services:
  frontend:
    image: village-sim_frontend
    build: frontend
    container_name: vill-sim-frontend
    restart: unless-stopped
    network_mode: host

  backend:
    image: village-sim_backend
    container_name: vill-sim-backend
    restart: unless-stopped
    build: backend
    volumes:
      - ./backend/src:/src
    ports:
      - "8000:8000"
